version: "3"

services:
  node:
    image: node:16
    # Nome do container para facilitar execução
    container_name: one_for_all
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    # Substitui o comando padrão da imagem do node
    command: bash
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório dos desafios e dos testes dentro do diretório /app
      - ./:/app
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306

  db:
    container_name: one_for_all_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: one_for_all_net
